### ISSUE TITLE
Generic mirror surface shape parameter bug with user  value "incidence angle respective to normal [deg]"

### ISSUE THREAD

**Issue by xianbo** [oasys-kit/shadow4#16]
For curved mirror, when use internal/calculated type for surface shape parameter, when the incidence angle is set to "User value", in the field of "Incident angle respect to normal [deg]", one has to input the grazing incident angle relative to surface instead of the incident angle.

**Comment by srio** [comment]
Fixed. Thanks for all your helpful comments!
