### ISSUE TITLE
Crystal energy resolution

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/shadow4#18]
I do not know how relevant is this, but there seems to be a trend in the different energy resolutions between SHADOW3 and 4:
https://github.com/oasys-kit/shadow4workspaces/blob/main/reyes_id21_SXMII_shadow4_test.ows

![image](https://github.com/oasys-kit/shadow4/assets/31166917/57961d08-ac3c-44da-a063-5cc6e364b9b2)

First for a Si(111) in the (+,+) config:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/1ca8be67-4d45-4019-b193-83a1ff90d7ce)
Then, the difference is more clear for Si(333) in the same (+,+) config:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/781d1a37-7869-42f2-8088-296bff095784)

**Comment by srio** [comment]
It is important. It seems shadow4 is using +- instead of ++. I will look into it.

**Comment by srio** [comment]
Fixed ( https://github.com/oasys-kit/shadow4/commit/05b6d7739a825f8e83bcf84b998ad89ce6391ca7 )
