### ISSUE TITLE
Wiggler source error 

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/shadow4#19]
There is an error on wiggler source OASYS1-SHADOW4 widget:
`TypeError                                     Traceback (most recent call last):
  File "C:\...\OASYS1-SHADOW4\orangecontrib\shadow4\widgets\sources\ow_wiggler.py", line 300, in run_shadow4
    light_source = self.get_lightsource()
  File "C:\...\OASYS1-SHADOW4\orangecontrib\shadow4\widgets\sources\ow_wiggler.py", line 240, in get_lightsource
    epse_dz                  = self.epsi_dz,
TypeError: __init__() got an unexpected keyword argument 'epse_dx'
`
After the error, the widget freezes showing a 0% completion on the window:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/f0064818-3ce9-49fb-af12-e60506950915)

**Comment by srio** [comment]
Indeed, there is a stupid misspelling bug. I fixed it. Thanks a lot.

There are however differences between shadow3 and shadow4 . I have to look at that in more detail. This is important for the EBS BM beamlines. 

I keep the issue open until completion. 

Thanks .

**Comment by jureyherrera** [comment]
Thank you, but no I have another error, from SHADOW4 for periodic magnetic field:
`from shadow4.sources.wiggler.s4_wiggler import S4Wiggler`

_source = S4Wiggler(
    magnetic_field_periodic  = 1,   # 0=external, 1=periodic    
    K_vertical        = 10.0,
    period_length     = 0.1,
    number_of_periods = 10, 
    emin              = 1000,   
    emax              = 2000,   
    ng_e              = 100,    
    ng_j              = 501 ,   
    flag_emittance    = 1, 
    shift_x_flag      = 0,
    shift_x_value     = 0.0,
    shift_betax_flag  = 0,
    shift_betax_value = 0.0,
    epsi_dx= 0.0,
    )_

I got:

`TypeError: __init__() got an unexpected keyword argument 'epsi_dx'`

**Comment by srio** [comment]
Probably is because shadow4 is not updated (must be in development mode, not yet in pypi).

PS: It is good to keep the issue open!
