### ISSUE TITLE
Friendly reminder: Refractive Lens Python script is not yet implemented

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/shadow4#24]
I was testing some Python scripts generated by SHADOW4 I just noticed it, this has been considered, so it is just a **friendly reminder**.

![image](https://github.com/oasys-kit/shadow4/assets/31166917/03e54bc2-698b-4aa5-8401-127a3dc3cbe7)

Greetings, J

**Comment by srio** [comment]
Done. Thanks Luca!
