### ISSUE TITLE
Display bug of preprocessors widgets

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/shadow4#32]
Hello,
There is a **_strange_** display bug in PreRefl and Bragg widgets, some input parameters boxes are too short, using the widgets in the OASYS GUI platform:

-  **RreRefl**:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/76a49a20-bc0a-436e-945a-8965710b7e2f)
- **Bragg**:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/5cec74a6-b5a1-45b3-b217-53afce8c573e)

It is **_strange_** because if we launch the widget GUIs from the code source, the box sizes are fine (as defined in the code):
 
![image](https://github.com/oasys-kit/shadow4/assets/31166917/1840a07a-2c57-4096-9941-b5defd83ba7e)

![image](https://github.com/oasys-kit/shadow4/assets/31166917/dac7fa19-324a-4f4f-8812-fdefb7fb4ef7)

I used Windows, but the issue is present in Linux as well:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/5eacb675-1fd5-4e11-b324-41ea260f4743)

Thank you,
Cheers, J

**Comment by srio** [comment]
I adjusted the labelWidth. Note that that I adjusted in my linux platform, and it may appear differently in Windows or Mac. Don't hesitate to reopen the issue if needed.
