### ISSUE TITLE
MLayer system output wrong values

### ISSUE THREAD

**Issue by xianbo** [oasys-kit/shadow4#40]
When running the MLayer for laterally graded coeffs from "calculate for an ellipse", the print out in the Output tab shows wrong ellipse a, b, c, ycen, zen, and a0, a1, a2, a3 values. An example is shown in the figure below. However, the output file can be used by the General Multilayer widget and give correct results. But if you use these printed a0-a3 values in "External definition", the results will be wrong. The correct coeffs for the example below should be {1.00001,-1.85812,-1.30306,-2.55142}.
![Screenshot 2024-10-04 170301](https://github.com/user-attachments/assets/a23863b9-4925-4e5b-ae4c-e264641478ec)

Also, looking into the mlayer.py code, line 1243, "y1 = numpy.linspace(ycen - mirrorlength, ycen + mirrorlength, 100)". Why not ycen-mirrorlength/2, ycen + mirrorlength/2?

**Comment by srio** [comment]
Thanks a lot for reporting this bug. Indeed there was a bug in printing/saving the results. Also, you are right in the mirrorlength (although the impact is irrelevant). Solved in the new updated shadow4 and OASYS1shadow4 (0.0.58)
